services:
  influxdb2:
    image: influxdb:2
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=test
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=collector
      - DOCKER_INFLUXDB_INIT_BUCKET=miners
    ports:
      - 8086:8086
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
  grafana:
    image: grafana/grafana-oss
    restart: always
    depends_on:
      - influxdb2
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-config:/etc/grafana
volumes:
  influxdb2-data:
  influxdb2-config:
  grafana-data: {}
  grafana-config: {}
